# Game Constants

FPS = 60
WINDOW_WIDTH = 800
WINDOW_HEIGHT = 600

# Color Constants
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)

# Player Constants
PLAYER_START_X = WINDOW_WIDTH // 2
PLAYER_START_Y = WINDOW_HEIGHT // 2
PLAYER_SPEED = 5
PLAYER_LIVES = 3

# Game State Constants
GAME_ACTIVE = 1
GAME_PAUSED = 2
GAME_OVER = 3

# Level Constants
LEVEL_COUNT = 10
MAX_ENEMIES_PER_LEVEL = 5

# Platform Constants
PLATFORM_COLOR = GREEN
PLATFORM_HEIGHT = 20
PLATFORM_WIDTH = 100

# Sound Constants
SOUNDTRACK_VOLUME = 0.5
SFX_VOLUME = 1.0